### PR TITLE
Update gem to pass with v2.8

### PR DESCRIPTION
**Pull request by fastjames**
Update the gem to pass under Solidus v2.8. This should provide a good
starting point for further updates to support Solidus v2.9 and beyond.
Changes made include:

1. Update TravisCI matrix to remove EOL Solidus versions
2. Update Rakefile to support standard `rake` task
3. Pin `sprockets` to <4 to avoid new breaking change
4. Add `puma` dev dependency for feature specs
5. Update factory to remove static attribute
6. Update reference to capybara wait time
7. Update feature spec to match option text and ordering as observed

### CODE REVIEW

**Comment by dhonig** [comment]
Tests are still failing.   Let us know if you need a hand with this.

**Comment by fastjames** [comment]
> Tests are still failing. Let us know if you need a hand with this.

Thanks for the heads-up. I took a look at some other extensions and updated the travis config to be more like those (since they are passing).

**Comment by fastjames** [comment]
@dhonig some progress -- the only two failing paths now are `v2.5` and `master`.

**Comment by fastjames** [comment]
It looks like `master` is failing because the `add_class` method was removed back in July: https://github.com/solidusio/solidus/commit/d82fb569ab2f4d79181473c35169813ab7c39e35

**Comment by fastjames** [comment]
The `v2.5` path is failing because it times out while running `bundle`.

**Comment by fastjames** [comment]
I just pushed a commit that passes locally for `master`. I didn't test it with other versions yet. Still no idea what's up with `v2.5`.

**Comment by fastjames** [comment]
Sorry this has taken so long -- I have not had much luck replicating these CI failures locally. Hopefully moving to selenium and headless chrome will help some of these since they seem to be possible browser-related.

**Comment by fastjames** [comment]
Let the record show that I have now gotten every branch to pass at least once, just not all on the same run. :rofl:

**Comment by fastjames** [comment]
I think I have taken too big of a bite here, so I'm going to close this PR and retrench on a more focused branch.

**Comment by fastjames** [comment]
Continued in https://github.com/boomerdigital/solidus_flexi_variants/pull/22

**Pull request closed without merging**
