### PR TITLE
Separate into3 engines

### PR DESCRIPTION
**Pull request by masonjeffreys**
Following the Solidus convention, this branch is a work in progress to separate the solidus_flexi_variants gem into: core, backend, and frontend engines so that they can be used independently.

### CODE REVIEW

**Comment by dhonig** [comment]
Thanks for this. Give us a few days  to review and comment.  Lots of people out for the holiday weekend so expect to hear something next week.

**Comment by masonjeffreys** [comment]
Sounds good. Thanks Daniel!
Jeff

**Comment by masonjeffreys** [comment]
Just a ping on this.

**Comment by dhonig** [comment]
@acreilly  can you take a look at this?

**Comment by acreilly** [comment]
Is there a way to run this through Travis?

**Comment by masonjeffreys** [comment]
Ping on this. Happy to tackle some more work if it's a direction you all do want to move in.

**Comment by dhonig** [comment]
@masonjeffreys Thanks, let me have @eric1234 or @kenton  comment on this before we spend more time on it.  I did look at it last week and thought it made sense, but want some more eyes on it.

**Comment by dhonig** [comment]
@masonjeffreys Thanks, let me have @eric1234 or @kenton  comment on this before we spend more time on it.  I did look at it last week and thought it made sense, but want some more eyes on it.

**Comment by dhonig** [comment]
@masonjeffreys Thanks, let me have @eric1234 or @kenton  comment on this before we spend more time on it.  I did look at it last week and thought it made sense, but want some more eyes on it.

**Comment by dhonig** [comment]
@masonjeffreys Thanks, let me have @eric1234 or @kenton  comment on this before we spend more time on it.  I did look at it last week and thought it made sense, but want some more eyes on it.

**Comment by dhonig** [comment]
@masonjeffreys Thanks, let me have @eric1234 or @kenton  comment on this before we spend more time on it.  I did look at it last week and thought it made sense, but want some more eyes on it.

**Comment by dhonig** [comment]
@masonjeffreys  let's ask @kenton or @eric1234   I think its a good direction but want to have some more eyes on it before we move forward.

**Comment by eric1234** [comment]
Looking through this I see some good cleanup :+1:

As to the splitting into three engines to mirror the organization structure of Spree/Solidus itself I don't really have a strong opinion. In theory someone could load just the core or just the core + backend but I don't really see any big gain in doing that. IMHO the three distinct engines don't offer any real advantage over just using namespaces (as it was already doing) and it slightly increases the amount of boilerplate.

That being said the same strategy is used in Spree/Solidus so I wouldn't even flinch if I saw this separation in a plugin. I don't think the three engines come with any real disadvantage so I wouldn't discourage it either.

**Comment by masonjeffreys** [comment]
Thanks for the comments @eric1234 . The reason I requested this change was that I wanted to use solidus_flexi_variants but I was not using a conventional Solidus frontend. Solidus_flexi_variants seemed to make assumptions that I was using the conventional solidus frontend (it assumed specific controller naming I believe).

Perhaps there is another, easier way to let folks use this gem with a custom solidus frontend.

**Comment by masonjeffreys** [comment]
All,
Haven't seen much movement on this. Perhaps there's an easier way to achieve the same result? Maybe adding some optional config to be able to exclude the frontend pieces of the gem?
I'm just looking for a way to use this with a custom frontend.
Up for suggestions.

**Comment by masonjeffreys** [comment]
Closing this pull request in favor of a new approach that adds conditional statements to the frontend decorators so that people can use the gem without a standard solidus frontend.

**Pull request closed without merging**
